### PR TITLE
a few typos+

### PR DESCRIPTION
**Pull request by robi-y**
On an more general comment, It seems the ideas in the subsection: ```### Composition is not a single DSL, but a series of mini DSLs``` 
are very close to the DDD notion of 'Bounded Context'.

### CODE REVIEW

**Comment by grzesiek-galezowski** [comment]
Thanks for the typos! 

Also, thank you for the general comment - I was really hoping for a feedback like this, since I am still learning in this field. I skimmed through the description of bounded context and it seems like there are similarities indeed. On the other hand, reading an example, I got a feeling that bounded contexts deal with higher level division than what I was writing about, but maybe that was just this example and maybe the notion of bounded context can be scaled up and down? What do you think?

I am still finishing Fowler's DSL book and DDD is next on my list, so hopefully I am going to learn more about this. For now, I think I might include a reference in the book pointing that the ideas are related.

**Comment by robi-y** [comment]
I'm also not an expert but it seem to fit nicely at least with this paragraph, so it's a good idea to at least reference it

**Comment by grzesiek-galezowski** [comment]
Added a reference, now I need to test and adjust the placement to make sure leanpub parses it correctly

**Comment by robi-y** [comment]
BTW, except for the standard book by Evans, there's a short one from infoq http://www.infoq.com/resource/minibooks/domain-driven-design-quickly and a new one by Vaughn Vernon that seems to follow other practices/notions we are having here http://vaughnvernon.co/?page_id=168

**Pull request merged**
