### PR TITLE
Fix a few typos and improve use of English in [040] and [070]

### PR DESCRIPTION
**Pull request by spmaniato**
~~@martinmoene~~ @grzesiek-galezowski Here's that pull request. Sorry for the delay.

Please let me know if you disagree with something and I will address it.

Cheers,
Spyros

### CODE REVIEW

**Comment by martinmoene** [comment]
Thanks Spyros (@spmaniato), 

May I humbly note that it's @grzesiek-galezowski who is writing the book, so maybe it's better to address him ;) I was just trying to make sure your PR-to-be would make it through.

Thanks again & cheers,
Martin

**Comment by spmaniato** [comment]
Oops. Thanks for pointing that out :+1:

**Comment by grzesiek-galezowski** [comment]
Thanks for the pull request! This week is busy for me - I'll try to review and merge it tomorrow or on Wednesday :-).

**Comment by grzesiek-galezowski** [comment]
I am merging the pull request. Thank you for the corrections!

**Comment by spmaniato** [comment]
Great! Thank you for the book. I'm really enjoying it :smiley:

**Comment by grzesiek-galezowski** [comment]
Thank you for your help in making it better!

**Pull request merged**
