### PR TITLE
Change some subsections into sections (Statement-first programming)

### PR DESCRIPTION
**Pull request by martinmoene**
Aim for a table of contents that reads as an overview of the book.

Perhaps try to find a shorter title for *Not starting from specification leads to waste of time on making objects testable*.

### CODE REVIEW

**Comment by martinmoene** [comment]
Oh, forgot to emphasize that a PR is an invitation to a discussion (if so desired), despite the way its title is written.

cheers,
Martin

**Comment by grzesiek-galezowski** [comment]
This one is more problematic than others. My original intention for nesting was:
```
## The benefit of failure
### You do not know whether the Statement can ever be false until you see it evaluate as false
#### 1. Accidental omission of adding a Statement to Specification
#### 2. Misplacing mock setup
#### 3. Using static data inside production code
### “Test-After" ends up as “Test-Never" 
### Not starting from specification leads to waste of time on making objects testable
```

Although as I look at it now, I get your point that this nesting looks misleading as the last two topics do not discuss benefits of seeing a test fail.

I will submit an issue to remind myself to better structure this chapter. For now, I suggest the following names:

```
## "Test First" means seeing a failure
### You do not know whether the Statement can ever be false until you see it evaluate as false
#### 1. Accidental omission of adding a Statement to Specification
#### 2. Misplacing mock setup
#### 3. Using static data inside production code
## “Test-After" ends up as “Test-Never" 
## "Test-After" leads to design rework
```

What do you think?

Still the structure of the chapter needs a bit of work.

**Comment by martinmoene** [comment]
Excellent: *"Test-After" leads to design rework*

I've updated the PR.

**Comment by martinmoene** [comment]
Oops not all changes included

...Working...

**Comment by martinmoene** [comment]
I've updated the PR (again).

**Pull request merged**
