### PR TITLE
Typo was corrected: enum?? -> enum?

### PR DESCRIPTION
**Pull request by rafalbig**
Minor change.

### CODE REVIEW

**Comment by grzesiek-galezowski** [comment]
@rafalbig thank you for your contributions! I want to add you to the "thank you" list inside the book. I can use your nick or if you give me your name, I could use that. Thanks again for taking the time to improve the book!

**Comment by rafalbig** [comment]
Hi @grzesiek-galezowski. My name is Rafał Bigaj. Reading your book is a great opportunity to learn something valuable. I'll keep my fingers crossed for you. Cheers.

**Comment by grzesiek-galezowski** [comment]
Added your name with committ e0791347fbe10bdad50220838ad90056511e2999

Thank you for your contributions and looking forward to maybe some more in the future. I'm happy you find the book interesting!

**Comment by rafalbig** [comment]
@grzesiek-galezowski  Thank you.

**Pull request merged**
