### PR TITLE
Improve style in 030_Motivations.md

### PR DESCRIPTION
**Pull request by martinmoene**
>And it’s not something I can use only when I pay to Microsoft or Oracle or anybody else

I take this to mean: *I can apply TDD regardless whom I'm working for*, but I'm not sure if above phrase 1) is meant to say that and 2) if it does say so.

### CODE REVIEW

**Comment by grzesiek-galezowski** [comment]
"And it’s not something I can use only when I pay to Microsoft or Oracle or anybody else" meant that it is a skill, not a technology, and as such, it is more "portable". I suggest to change the following:

"And it’s not something I can use only when I pay to Microsoft or Oracle or anybody else -- it’s quite portable, making me a better developer overall!"

to: 
"And it is a skill that I can apply to many different technologies and languages, making me a better developer overall!"

What do you think?

**Comment by grzesiek-galezowski** [comment]
By the way, I did what github told me to resolve conflicts, but it does not say that I merged this pull request. Strange...

**Comment by martinmoene** [comment]
Looks like you merged the changes successfully.

**Comment by martinmoene** [comment]
>"And it is a skill that I can apply to many different technologies and languages, making me a better developer overall!"

Yes, that's clear.

**Comment by grzesiek-galezowski** [comment]
I think I got the changed, but it does not say that it is a merged pull request. Anyway, thank you for the changes, I will apply the last correction in a minute.

**Comment by martinmoene** [comment]
Looks Ok to me.

**Pull request closed without merging**
